---
# tasks file for nutanix_role_prism_dns
  - name: Get current DNS configuration
    uri:
      url: "{{ prism_api_v2 }}/cluster/name_servers"
      method: GET
      validate_certs: "{{ validate_certs }}"
      body_format: json
      headers:
        Authorization: "{{ prism_api_auth }}"
      return_content: yes
    register: prism_dns_current_config
    when:
      - item not in prism_dns_current_config

  - name: Remove configured DNS servers not in desired configuration
    uri:
      url: "{{ prism_api_v2 }}/cluster/name_servers/{{ item }}"
      method: DELETE
      validate_certs: "{{ validate_certs }}"
      body_format: json
      headers:
        Authorization: "{{ prism_api_auth }}"
      return_content: yes
      status_code: 204
    when: item not in prism_dns_server_list
    changed_when: true
    register: prism_dns_remove_missing_entry
    ignore_errors: true
    with_items: "{{ prism_dns_current_config }}"

  - name: Set DNS server addresses
    uri:
      url: "{{ prism_api_v2 }}/cluster/name_servers"
      method: POST
      validate_certs: "{{ validate_certs }}"
      body:
        value: "{{ item }}"
      body_format: json
      headers:
        Authorization: "{{ prism_api_auth }}"
      return_content: yes
      status_code: 200,201
    with_items: "{{ prism_dns_server_list }}"
    changed_when: true
    register: prism_dns_update
    ignore_errors: true
    when: item not in prism_dns_current_config
